### PR TITLE
Add support for Kibana 5.5.0

### PR DESCRIPTION
**Pull request by fbaligand**

### CODE REVIEW

**Comment by fbaligand** [comment]
Hi @PhaedrusTheGreek,

I push this PR to provide support for Kibana 5.5.0.

**Comment by fbaligand** [comment]
Thanks for the merge !

**Comment by PhaedrusTheGreek** [comment]
Thanks for the PR, very very helpful and much appreciated.

**Comment by fbaligand** [comment]
Nice to see you appreciate !
And thanks for your plugin, which is very helpful !

**Pull request merged**
